Nop.Plugin.Widgets.SalesCampaigns/Models/PreviewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Nop.Plugin.Widgets.SalesCampaigns.Models
{
    public partial record PreviewModel : BaseNopEntityModel
    {
        public PreviewModel()
        {
            PreviewSearchModel = new PreviewSearchModel();
        }
        #region Properties

        [NopResourceDisplayName("Plugins.Widgets.SalesCampaigns.Fields.SalesCampaigns")]
        public int SalesCampaignsId { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.SalesCampaigns.Fields.Product")]
        public int ProductId { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.SalesCampaigns.Fields.Product")]
        public string ProductName { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.SalesCampaigns.Fields.Price")]
        public decimal Price { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.SalesCampaigns.Fields.SalePrice")]
        public decimal SalePrice { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.SalesCampaigns.Fields.OverrideCentsValue")]
        [Range(0.1, 0.99)]
        [RegularExpression(@"^\d+(.\d{0,2})?$")]
        public decimal OverrideCentsValue { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.SalesCampaigns.Fields.DiscountType")]
        public int DiscountTypeId { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.SalesCampaigns.Fields.SearchDiscountType")]
        public IList<SelectListItem> AvailableDiscountType { get; set; }

        [NopResourceDisplayName("Plugins.Widgets.SalesCampaigns.Fields.OverrideCents")]
        public bool OverrideCents { get; set; }
        public PreviewSearchModel PreviewSearchModel { get; set; }

        #endregion
    }
}

Nop.Plugin.Widgets.SalesCampaigns/Controllers/SalesCampaignsController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Cms;
using Nop.Plugin.Widgets.SalesCampaigns.Domain;
using Nop.Plugin.Widgets.SalesCampaigns.Factories;
using Nop.Plugin.Widgets.SalesCampaigns.Models;
using Nop.Plugin.Widgets.SalesCampaigns.Services;
using Nop.Services.Catalog;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;
using System;
using System.Linq;
using System.Threading.Tasks;


namespace Nop.Plugin.Widgets.SalesCampaigns.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    [AutoValidateAntiforgeryToken]
    public class SalesCampaignsController : BasePluginController
    {
        #region Fields
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IPictureService _pictureService;
        private readonly ISalesCampaignsModelFactory _salesCampaignsModelFactory;
        private readonly ISalesCampaignsService _salesCampaignsService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly ISalesCampaignsService _salesCampaigns;
        #endregion

        #region Ctor
        public SalesCampaignsController(ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IPictureService pictureService,
            ISalesCampaignsModelFactory salesCampaignsModelFactory,
            ISalesCampaignsService salesCampaignsService,
            ISettingService settingService,
            IStoreContext storeContext,
            ICategoryService categoryService,
            IProductService productService,
            ISalesCampaignsService salesCampaigns)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _pictureService = pictureService;
            _salesCampaignsModelFactory = salesCampaignsModelFactory;
            _salesCampaignsService = salesCampaignsService;
            _settingService = settingService;
            _storeContext = storeContext;
            _categoryService = categoryService;
            _productService = productService;
            _salesCampaigns = salesCampaigns;
        }

        #endregion

        #region Configure
        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var storeId = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var settings = await _settingService.LoadSettingAsync<SalesCampaignsSettings>(storeId);
            var widgetSettings = await _settingService.LoadSettingAsync<WidgetSettings>(storeId);

            var model = new ConfigurationModel
            {
                Enable = settings.Enable,
                ActiveStoreScopeConfiguration = storeId
            };

            if (storeId > 0)
            {
                model.Enable_OverrideForStore = await _settingService.SettingExistsAsync(widgetSettings, setting => setting.ActiveWidgetSystemNames, storeId);
            }

            return View("~/Plugins/Widgets.SalesCampaigns/Views/Admin/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();


            var storeId = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var settings = await _settingService.LoadSettingAsync<SalesCampaignsSettings>(storeId);
            var widgetSettings = await _settingService.LoadSettingAsync<WidgetSettings>(storeId);

            if (!ModelState.IsValid)
                return await Configure();


            settings.Enable = model.Enable;
            await _settingService.SaveSettingAsync(settings);


            if (model.Enable && !widgetSettings.ActiveWidgetSystemNames.Contains(SalesCampaignsDefaults.SystemName))
                widgetSettings.ActiveWidgetSystemNames.Add(SalesCampaignsDefaults.SystemName);
            if (!model.Enable && widgetSettings.ActiveWidgetSystemNames.Contains(SalesCampaignsDefaults.SystemName))
                widgetSettings.ActiveWidgetSystemNames.Remove(SalesCampaignsDefaults.SystemName);
            await _settingService.SaveSettingOverridablePerStoreAsync(widgetSettings, setting => setting.ActiveWidgetSystemNames, model.Enable_OverrideForStore, storeId, false);

            await _settingService.ClearCacheAsync();

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }
        #endregion

        #region List/Create/Edit/Delete/View
        public async Task<IActionResult> List()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            // prepare model
            var model = await _salesCampaignsModelFactory.PrepareSalesCampaignsSearchModelAsync(new SalesCampaignsSearchModel());
            return View("~/Plugins/Widgets.SalesCampaigns/Views/Admin/List.cshtml", model);

        }

        [HttpPost]
        public virtual async Task<IActionResult> List(SalesCampaignsSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            //prepare model
            var model = await _salesCampaignsModelFactory.PrepareSalesCampaignsListsModelAsync(searchModel);
            return Json(model);
        }

        public virtual async Task<IActionResult> Create()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            //prepare model
            var model = await _salesCampaignsModelFactory.PrepareSalesCampaignsModelAsync(new SalesCampaignsModel(), null);
            return View("~/Plugins/Widgets.SalesCampaigns/Views/Admin/Create.cshtml", model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [ValidateAntiForgeryToken]
        public virtual async Task<IActionResult> Create(SalesCampaignsModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {             
                var salesCampaigns = new SalesCampaignTable();
                salesCampaigns.Id = model.Id;
                salesCampaigns.Name = model.Name;
                #region  Comment Category part 
                //salesCampaigns.AssignToCategory = model.AssignToCategory;
                //salesCampaigns.CategoryId = model.SearchCategoryId;
                #endregion
                salesCampaigns.WidgetZoneId = model.WidgetZoneId;
                salesCampaigns.DiscountTypeId = model.DiscountTypeId;
                salesCampaigns.DiscountValue = model.DiscountValue;
                salesCampaigns.OverrideCents = model.OverrideCents;
                salesCampaigns.OverrideCentsValue = model.OverrideCentsValue;
                //extra columns
                salesCampaigns.ClockTypeId = model.ClockTypeId;
                salesCampaigns.FromDate = Convert.ToDateTime(model.FromDate);
                salesCampaigns.ToDate = Convert.ToDateTime(model.ToDate);
                salesCampaigns.FromTime = Convert.ToDateTime(model.FromTime);
                salesCampaigns.ToTime = model.ToTime;
                if(salesCampaigns.SchedulePatternTypeId == 0)
                {
                    salesCampaigns.SchedulePatternTypeId = (int)SchedulePatternType.Everyday;
                }
                else
                {
                    salesCampaigns.SchedulePatternTypeId = model.SchedulePatternTypeId;
                }
               
                salesCampaigns.Price = model.Price;

                //set default values for the new model
                if (salesCampaigns.CampaignStateId == 0)
                {
                    salesCampaigns.CampaignStateId = (int)CampaignStateType.Pending;  //assign value
                }

                await _salesCampaignsService.InsertSalesCampaignsAsync(salesCampaigns);


                if (!continueEditing)
                    return RedirectToAction("List");

                return RedirectToAction("Edit", new { id = salesCampaigns.Id });

            }
            //prepare model
            model = await _salesCampaignsModelFactory.PrepareSalesCampaignsModelAsync(model, null);
            return View("~/Plugins/Widgets.SalesCampaigns/Views/Admin/Create.cshtml", model);
        }

        public virtual async Task<IActionResult> Edit(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            //try to get a salesCampaigns with the specified id
            var salesCampaigns = await _salesCampaignsService.GetSalesCampaignsByIdAsync(id);

Nop.Plugin.Widgets.SalesCampaigns/Views/Admin/Configure.cshtml
@using Nop.Plugin.Widgets.SalesCampaigns.Models
@model ConfigurationModel

@{
    Layout = "_AdminLayout";
    ViewBag.PageTitle = T("Plugins.Widgets.SalesCampaigns.Menu.Settings").Text;
    NopHtml.SetActiveMenuItemSystemName("SalesCampaigns.Settings");
}

<form asp-controller="SalesCampaigns" asp-action="Configure" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Plugins.Widgets.SalesCampaigns.Admin.Configuration.Settings")
        </h1>
    </div>
    <section class="content">
        <div class="cards-group">
            <div class="card card-default">

                <div class="card-body">
                    <div class="form-group row">
                        <div class="col-md-1 text-right">
                            <nop-editor asp-for="Enable" />
                            <span asp-validation-for="Enable"></span>
                        </div>
                        <div class="col-md-2">
                            <nop-override-store-checkbox asp-for="Enable_OverrideForStore" asp-input="Enable" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                            <nop-label asp-for="Enable" />
                        </div>
                        <div class="col-md-9">
                            <input type="submit" name="save" class="btn btn-primary svbtn" value="Save" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>

Nop.Plugin.Widgets.SalesCampaigns/Views/Admin/Create.cshtml
@using Nop.Plugin.Widgets.SalesCampaigns.Models
@using Nop.Web.Framework.Infrastructure
@using Nop.Web.Framework.UI
@model SalesCampaignsModel
@{
    Layout = "_AdminLayout";
}

<form asp-controller="SalesCampaigns" asp-action="Create" method="post" id="salesCampaigns-form">
    <div class="form-horizontal">
        <div class="content-header clearfix">
            <h1 class="float-left">
                @T("Plugins.Widgets.SalesCampaigns.AddNew")
                <small>
                    <i class="fas fa-arrow-circle-left"></i>
                    <a asp-action="List">@T("Plugins.Widgets.SalesCampaigns.BackToList")</a>
                </small>
            </h1>
            <div class="float-right">
                <button type="submit" name="save" class="btn btn-primary">
                    <i class="far fa-save"></i>
                    @T("Admin.Common.Save")
                </button>
                <button type="submit" name="save-continue" class="btn btn-primary">
                    <i class="far fa-save"></i>
                    @T("Admin.Common.SaveContinue")
                </button>
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.WidgetListButtons, additionalData = Model })
            </div>
        </div>

        @(await Html.PartialAsync("~/Plugins/Widgets.SalesCampaigns/Views/Admin/ConfigurePage.cshtml", Model))
    </div>
</form>

Nop.Plugin.Widgets.SalesCampaigns/Views/Admin/Edit.cshtml
@using Nop.Plugin.Widgets.SalesCampaigns.Models
@using Nop.Web.Framework.Infrastructure
@using Nop.Web.Framework.UI
@model SalesCampaignsModel
@{
    Layout = "_AdminLayout";
}

<form asp-controller="SalesCampaigns" asp-action="Edit" method="post" id="salesCampaigns-form">
    <div class="form-horizontal">
        <div class="content-header clearfix">
            <h1 class="float-left">
                @T("Plugins.Widgets.SalesCampaigns.Edit")
                <small>
                    <i class="fas fa-arrow-circle-left"></i>
                    <a asp-action="List">@T("Plugins.Widgets.SalesCampaigns.BackToList")</a>
                </small>
            </h1>
            <div class="float-right">
                <button type="submit" name="save" class="btn btn-primary">
                    <i class="far fa-save"></i>
                    @T("Admin.Common.Save")
                </button>
                <button type="submit" name="save-continue" class="btn btn-primary">
                    <i class="far fa-save"></i>
                    @T("Admin.Common.SaveContinue")
                </button>
                <span id="salesCampaigns-delete" class="btn btn-danger">
                    <i class="far fa-trash-alt"></i>
                    @T("Admin.Common.Delete")
                </span>
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.WidgetListButtons, additionalData = Model })
            </div>
        </div>

        @(await Html.PartialAsync("~/Plugins/Widgets.SalesCampaigns/Views/Admin/ConfigurePage.cshtml", Model))
    </div>
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="salesCampaigns-delete" />

Nop.Plugin.Widgets.SalesCampaigns/Views/Admin/List.cshtml
@inject Nop.Core.Domain.Common.AdminAreaSettings adminAreaSettings
@using Nop.Plugin.Widgets.SalesCampaigns.Models
@using Nop.Plugin.Widgets.SalesCampaigns.Domain
@using Nop.Web.Framework.Models.DataTables
@model SalesCampaignsSearchModel
@using Nop.Core
@inject Nop.Services.Common.IGenericAttributeService genericAttributeService
@inject IWorkContext workContext
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "_AdminLayout";
    ViewBag.PageTitle = T("Plugins.Widgets.SalesCampaigns.Admin.Manage.Settings").Text;
    NopHtml.SetActiveMenuItemSystemName("SalesCampaigns.List");
}
<form asp-controller="SalesCampaigns" asp-action="List" method="post" id="salesCampaigns-form">
    <div class="content-header clearfix">

        <h4 class="float-left">
            @T("Plugins.Widgets.SalesCampaigns.Admin.Configuration.Settings")
        </h4>

        <div class="float-right">
            <a asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus-square"></i>
                @T("Admin.Common.AddNew")
            </a>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.WidgetListButtons, additionalData = Model })
        </div>
    </div>


    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <nop-cards id="salesCampaigns-cards">

                    <div class="card card-default">
                        <div class="card-body">
                            <p>
                                @Html.Raw(string.Format(T("Plugins.Widgets.SalesCampaigns.Fields.Instructions").Text, webHelper.GetStoreLocation()))
                            </p>
                            <hr />
                        </div>
                    </div>
                    <div class="cards-group">
                        <div class="card card-default">
                            <div class="card-body">
                                @await Html.PartialAsync("Table", new DataTablesModel
                           {
                               Name = "salesCampaigns-grid",
                               UrlRead = new DataUrl("List", "SalesCampaigns", null),
                               UrlDelete = new DataUrl("Delete", "SalesCampaigns", null),
                               SearchButtonId = "search-records",
                               Length = Model.PageSize,
                               LengthMenu = Model.AvailablePageSizes,
                               Ordering = true,
                               ServerSide = false,
                               Filters = new List<FilterParameter>
                                            {
                                                new FilterParameter(nameof(Model.SearchCategoryId)),
                                            },
                               ColumnCollection = new List<ColumnProperty>
                                {
                                    new ColumnProperty(nameof(SalesCampaignsModel.Name))
                                    {
                                        Title = T("Plugins.Widgets.SalesCampaigns.Fields.Name").Text,
                                        Width = "200"
                                    },
                                       new ColumnProperty(nameof(SalesCampaignsModel.State))
                                    {
                                        Title = T("Plugins.Widgets.SalesCampaigns.Fields.State").Text,
                                        Width = "150"
                                    },
                                        new ColumnProperty(nameof(SalesCampaignsModel.FromDate))
                                        {
                                            Title = T("Plugins.Widgets.SalesCampaigns.Fields.FromDate").Text,
                                            Width = "120",
                                            Render = new RenderCustom("renderFromDate")
                                        },
                                     new ColumnProperty(nameof(SalesCampaignsModel.ToDate))
                                     {
                                         Title = T("Plugins.Widgets.SalesCampaigns.Fields.ToDate").Text,
                                         Width = "120",
                                         Render = new RenderCustom("renderToDate")
                                     },
                                     new ColumnProperty(nameof(SalesCampaignsModel.SchedulePattern))
                                    {
                                        Title = T("Plugins.Widgets.SalesCampaigns.Fields.SchedulePattern").Text,
                                        Width = "150"
                                    },
                                     new ColumnProperty(nameof(SalesCampaignsModel.ActionTypeId))
                                        {
                                            Title = T("Plugins.Widgets.SalesCampaigns.Fields.Action").Text,
                                            Width = "350",
                                            ClassName =  NopColumnClassDefaults.Button,
                                            Render = new RenderCustom("renderActionType")
                                       },
                                    new ColumnProperty(nameof(SalesCampaignsModel.Command))
                                    {
                                        Title = T("Plugins.Widgets.SalesCampaigns.Fields.Command").Text,
                                        Width = "100",
                                        ClassName =  NopColumnClassDefaults.Button,
                                        Render = new RenderCustom("renderColumnBtns")
                                    }

                               }
                           })

                            </div>
                            <script>

                                function renderActionType(data, type, row, meta) {
                                    var editlink = '@Url.Content("~/Admin/SalesCampaigns/Edit/")' + row.Id;
                                    var viewlink = '@Url.Content("~/Admin/SalesCampaigns/ViewSalesCampaigns/")' + row.Id;
                                    var schedule = '@Url.Content("~/Admin/SalesCampaigns/Schedule/")' + row.Id;
                                    var unschedule = '@Url.Content("~/Admin/SalesCampaigns/Schedule/")' + row.Id;
                                    var start = '@Url.Content("~/Admin/SalesCampaigns/StartImmediately/")' + row.Id;
                                    var stop = '@Url.Content("~/Admin/SalesCampaigns/StartImmediately/")' + row.Id;

                                    if (row.CampaignStateId == @((int)CampaignStateType.Pending)) {
                                        return '<a class="btn btn-default"  href="' + schedule + '"><i class="k-icon k-i-calendar"></i> @T("Plugins.Widgets.SalesCampaigns.Fields.Action.Schedule").Text</a>  <a class="btn btn-default"  href="' + start + '"><i class="k-icon k-i-arrow-e"></i>@T("Plugins.Widgets.SalesCampaigns.Fields.Action.StartImmediately").Text</a>';
                                    }
                                    else if (row.CampaignStateId == @((int)CampaignStateType.Scheduled)) {
                                        return '<a class="btn btn-default"  href="' + unschedule + '"><i class="k-icon k-i-exception"></i> @T("Plugins.Widgets.SalesCampaigns.Fields.Action.Unschedule").Text</a>  <a class="btn btn-default"  href="' + start + '"><i class="k-icon k-i-arrow-e"></i>@T("Plugins.Widgets.SalesCampaigns.Fields.Action.StartImmediately").Text</a>';
                                    }
                                    else if (row.CampaignStateId == @((int)CampaignStateType.Running)) {
                                        return '<a class="btn btn-default"  href="' + stop + '"><i class="k-icon k-i-exception"></i> @T("Plugins.Widgets.SalesCampaigns.Fields.Action.StopImmediately").Text</a>';
                                    }
                                }

                                function renderColumnBtns(data, type, row, meta) {
                                    var editlink = '@Url.Content("~/Admin/SalesCampaigns/Edit/")' + row.Id;
                                    var viewlink = '@Url.Content("~/Admin/SalesCampaigns/ViewSalesCampaigns/")' + row.Id;
                                    if (row.CampaignStateId == @((int)CampaignStateType.Pending)) {
                                        return '<a class="btn btn-default"  href="' + editlink + '"><i class="fas fa-pencil-alt"></i> @T("Plugins.Widgets.SalesCampaigns.Edit").Text</a>';
                                    }
                                    else if (row.CampaignStateId == @((int)CampaignStateType.Scheduled) || row.CampaignStateId == @((int)CampaignStateType.Running) ) {
                                        return '<a class="btn btn-default"  href="' + viewlink + '"><i class="far fa-eye"></i> @T("Plugins.Widgets.SalesCampaigns.View").Text</a>';
                                    }
                                }

                                function renderFromDate(data, type, row, meta) {
                                    if (data == '0001-01-01T00:00:00') {
                                        return "N/A";
                                    }
                                    return data.replace('T00:00:00', '');
                                }

                                function renderToDate(data, type, row, meta) {
                                    if (data == '0001-01-01T00:00:00') {
                                        return "N/A";
                                    }
                                    return data.replace('T00:00:00', '');
                                }
                            </script>

                         
                            <nop-alert asp-alert-id="deleteSelectedFailed" />
                            <nop-alert asp-alert-id="nothingSelectedAlert" />
                        </div>
                    </div>

                </nop-cards>
            </div>
        </div>
    </section>
</form>

Nop.Plugin.Widgets.SalesCampaigns/Views/Admin/Preview.cshtml
@model Nop.Plugin.Widgets.SalesCampaigns.Models.SalesCampaignsModel
@inject Nop.Core.IWebHelper webHelper
@inject IStoreService storeService
@using Nop.Plugin.Widgets.SalesCampaigns.Domain
@using Nop.Core.Domain.Catalog;
@using Nop.Services
@using Nop.Services.Stores
@using Nop.Web.Areas.Admin.Models.Catalog
@using Nop.Plugin.Widgets.SalesCampaigns.Models
@{
    Layout = "";
}
<link rel="stylesheet" href="~/Plugins/Widgets.SalesCampaigns/Content/css/SalesCampaigns.css" />
<input asp-for="Id" type="hidden" />


<div class="preview_note">
    <nop-cards id="salesCampaignspreview-cards">
        <div class="card card-default">
            <div class="card-body">
                <p>
                    @Html.Raw(string.Format(T("Plugins.Widgets.SalesCampaigns.Fields.Preview.Note").Text, webHelper.GetStoreLocation()))
                </p>
            </div>
        </div>
    </nop-cards>
</div>




@if (Model.Id > 0)
{
    <div class="card-body">
        @await Html.PartialAsync("Table", new DataTablesModel
   {
       Name = "preview-grid",
       UrlRead = new DataUrl("SalesCampaignsProductPreviewList", "SalesCampaigns", new RouteValueDictionary { [nameof(Model.PreviewSearchModel.SalesCampaignId)] = Model.Id }),
       SearchButtonId = "search-products",
       Length = Model.PreviewSearchModel.PageSize,
       LengthMenu = Model.PreviewSearchModel.AvailablePageSizes,
       ColumnCollection = new List<ColumnProperty>
            {
                new ColumnProperty(nameof(SalesCampaignsProductModel.ProductName))
                {
                    Title = T("Admin.Catalog.Products.Fields.Name").Text
                },
                 new ColumnProperty(nameof(SalesCampaignsProductModel.Price))
                 {
                     Title = T("Admin.Catalog.Products.Fields.Price").Text
                 },
                  new ColumnProperty(nameof(SalesCampaignsProductModel.SalePrice))
                 {
                     Title = T("Plugins.Widgets.SalesCampaigns.Fields.SalePrice").Text
                 }
            }
   })
    </div>
}
else
{
<div class="card-body">
    @T("Plugins.Widgets.SalesCampaigns.Categories.Products.SaveBeforeEdit")
</div>
}

Nop.Plugin.Widgets.SalesCampaigns/Views/Admin/View.cshtml
@using Nop.Plugin.Widgets.SalesCampaigns.Models
@using Nop.Web.Framework.Infrastructure
@using Nop.Web.Framework.UI
@model SalesCampaignsModel
@{
    Layout = "_AdminLayout";
}

<form asp-controller="SalesCampaigns" asp-action="ViewSalesCampaigns" method="post" id="salesCampaigns-form">
    <div class="form-horizontal">
        <div class="content-header clearfix">
            <h1 class="float-left">
                @T("Plugins.Widgets.SalesCampaigns.View")
                <small>
                    <i class="fas fa-arrow-circle-left"></i>
                    <a asp-action="List">@T("Plugins.Widgets.SalesCampaigns.BackToList")</a>
                </small>
            </h1>
            <div class="float-right">
                <button type="submit">

                    <i class="fas fa-arrow-circle-left"></i>
                    <a asp-action="List">@T("Plugins.Widgets.SalesCampaigns.BackToList")</a>

                </button>

                @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.WidgetListButtons, additionalData = Model })
            </div>
        </div>

        @(await Html.PartialAsync("~/Plugins/Widgets.SalesCampaigns/Views/Admin/ConfigurePage.cshtml", Model))
    </div>
</form>